In [86]:
import pandas as pd
import seaborn as sns
import numpy as np
import matplotlib.pyplot as plt
from sklearn.model_selection import train_test_split
from sklearn.datasets import load_iris
from sklearn.naive_bayes import GaussianNB,MultinomialNB,BernoulliNB
from sklearn.metrics import accuracy_score,classification_report,confusion_matrix
from sklearn.preprocessing import LabelEncoder,OneHotEncoder

In [87]:
X,y = load_iris(return_X_y=True)

In [88]:
X_train,X_test,y_train,y_test = train_test_split(X,y,test_size=0.3,random_state=10)

In [89]:
gnb = GaussianNB()

In [90]:
gnb.fit(X_train,y_train)
y_pred = gnb.predict(X_test)

In [91]:
print(accuracy_score(y_test,y_pred))
print(classification_report(y_test,y_pred))
print(confusion_matrix(y_test,y_pred))

1.0
              precision    recall  f1-score   support

           0       1.00      1.00      1.00        14
           1       1.00      1.00      1.00        17
           2       1.00      1.00      1.00        14

    accuracy                           1.00        45
   macro avg       1.00      1.00      1.00        45
weighted avg       1.00      1.00      1.00        45

[[14  0  0]
 [ 0 17  0]
 [ 0  0 14]]

# TIPS DATASET

In [92]:
df = sns.load_dataset('tips')
df

     total_bill   tip     sex smoker   day    time  size
0         16.99  1.01  Female     No   Sun  Dinner     2
1         10.34  1.66    Male     No   Sun  Dinner     3
2         21.01  3.50    Male     No   Sun  Dinner     3
3         23.68  3.31    Male     No   Sun  Dinner     2
4         24.59  3.61  Female     No   Sun  Dinner     4
..          ...   ...     ...    ...   ...     ...   ...
239       29.03  5.92    Male     No   Sat  Dinner     3
240       27.18  2.00  Female    Yes   Sat  Dinner     2
241       22.67  2.00    Male    Yes   Sat  Dinner     2
242       17.82  1.75    Male     No   Sat  Dinner     2
243       18.78  3.00  Female     No  Thur  Dinner     2

[244 rows x 7 columns]

In [93]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 244 entries, 0 to 243
Data columns (total 7 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   total_bill  244 non-null    float64
 1   tip         244 non-null    float64
 2   sex         244 non-null    category
 3   smoker      244 non-null    category
 4   day         244 non-null    category
 5   time        244 non-null    category
 6   size        244 non-null    int64
dtypes: category(4), float64(2), int64(1)
memory usage: 7.4 KB

In [94]:
le = LabelEncoder()

In [95]:
df['size'].value_counts()

size
2    156
3     38
4     37
5      5
1      4
6      4
Name: count, dtype: int64

In [96]:
cols = ['sex','smoker','time']
for i in cols:
    df[i] = le.fit_transform(df[i])
df

     total_bill   tip  sex  smoker   day  time  size
0         16.99  1.01    0       0   Sun     0     2
1         10.34  1.66    1       0   Sun     0     3
2         21.01  3.50    1       0   Sun     0     3
3         23.68  3.31    1       0   Sun     0     2
4         24.59  3.61    0       0   Sun     0     4
..          ...   ...  ...     ...   ...   ...   ...
239       29.03  5.92    1       0   Sat     0     3
240       27.18  2.00    0       1   Sat     0     2
241       22.67  2.00    1       1   Sat     0     2
242       17.82  1.75    1       0   Sat     0     2
243       18.78  3.00    0       0  Thur     0     2

[244 rows x 7 columns]

In [97]:
ohe_day = OneHotEncoder()
# Encode 'time'
time_encoded = ohe_day.fit_transform(df[['day']]).toarray()
df3 = pd.DataFrame(time_encoded, columns=ohe_day.get_feature_names_out(['day']))

In [98]:
df = pd.concat((df,df3),axis=1)

In [99]:
df = df.drop(columns=['day'])

In [100]:
df

,total_bill,tip,sex,smoker,time,size,day_Fri,day_Sat,day_Sun,day_Thur
0,16.99,1.01,0,0,0,2,0.0,0.0,1.0,0.0
1,10.34,1.66,1,0,0,3,0.0,0.0,1.0,0.0
2,21.01,3.50,1,0,0,3,0.0,0.0,1.0,0.0
3,23.68,3.31,1,0,0,2,0.0,0.0,1.0,0.0
4,24.59,3.61,0,0,0,4,0.0,0.0,1.0,0.0
...,...,...,...,...,...,...,...,...,...,...
239,29.03,5.92,1,0,0,3,0.0,1.0,0.0,0.0
240,27.18,2.00,0,1,0,2,0.0,1.0,0.0,0.0
241,22.67,2.00,1,1,0,2,0.0,1.0,0.0,0.0
242,17.82,1.75,1,0,0,2,0.0,1.0,0.0,0.0
243,18.78,3.00,0,0,0,2,0.0,0.0,0.0,1.0

In [101]:
y = df['time']
X = df.drop(columns=['time'])

In [102]:
X_train,X_test,y_train,y_test = train_test_split(X,y,test_size=0.3,random_state=10)

In [103]:
gnb1 = GaussianNB()

In [104]:
gnb1.fit(X_train,y_train)
y_pred = gnb1.predict(X_test)
print(accuracy_score(y_test,y_pred))
print(classification_report(y_test,y_pred))
print(confusion_matrix(y_test,y_pred))

0.9594594594594594
              precision    recall  f1-score   support

           0       1.00      0.94      0.97        54
           1       0.87      1.00      0.93        20

    accuracy                           0.96        74
   macro avg       0.93      0.97      0.95        74
weighted avg       0.96      0.96      0.96        74

[[51  3]
 [ 0 20]]

In [105]:
mn = MultinomialNB()
mn.fit(X_train,y_train)
y_pred = mn.predict(X_test)
print(accuracy_score(y_test,y_pred))
print(classification_report(y_test,y_pred))
print(confusion_matrix(y_test,y_pred))

0.9594594594594594
              precision    recall  f1-score   support

           0       0.96      0.98      0.97        54
           1       0.95      0.90      0.92        20

    accuracy                           0.96        74
   macro avg       0.96      0.94      0.95        74
weighted avg       0.96      0.96      0.96        74

[[53  1]
 [ 2 18]]

In [106]:
bn = BernoulliNB()
bn.fit(X_train,y_train)
y_pred = bn.predict(X_test)
print(accuracy_score(y_test,y_pred))
print(classification_report(y_test,y_pred))
print(confusion_matrix(y_test,y_pred))

0.9594594594594594
              precision    recall  f1-score   support

           0       0.96      0.98      0.97        54
           1       0.95      0.90      0.92        20

    accuracy                           0.96        74
   macro avg       0.96      0.94      0.95        74
weighted avg       0.96      0.96      0.96        74

[[53  1]
 [ 2 18]]